### ISSUE TITLE
Remaining leaves

### ISSUE THREAD

**Issue by roidelapluie** [kalmanolah/yayata#11]
Would be great to have the number of leaves days left

**Comment by kalmanolah** [comment]
925r does not support managing leave allowance, since this would make complexity go through the roof. In addition, HR would have to manage these things in 2 places, and keep them in sync..

**Comment by roidelapluie** [comment]
untrue leaves are approved here. and we could add the nuber of allowed leaves in the contract objet ?

**Comment by raskas** [comment]
Leaves are a bit more complex.
There are different types of leaves and all of them have a max allowed. This distinction between these types of leaves are not introduced into Yayata for simplification.
The max allowed leaves is not contract related, it can differ per user per year.

It is therefore currently not in scope to add the maximum allowed leaves.
