### ISSUE TITLE
feat request: show the number of attachments in month view

### ISSUE THREAD

**Issue by roidelapluie** [kalmanolah/yayata#22]
Currently:

![att](https://user-images.githubusercontent.com/291750/45021544-1c08eb00-b032-11e8-94be-40e616e0289a.png)

Nice to have:

![att2](https://user-images.githubusercontent.com/291750/45021545-1ca18180-b032-11e8-8552-57cbbf33aed6.png)

**Comment by kalmanolah** [comment]
Implemented
